config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{ 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root  'home#index'

  resources :home, only:[:index] do
    collection do
      get 'chat', 'game', 'seek'
    end
  end
  resources :tweets do
    member do
      get 'discussion'
    end
    collection do
      get 'search'
    end
    resources :comments, only: [:create]
  end

  resources :users,  only:[:index, :show] do
    collection do
      get 'follow_team', 'follow_prefecture', 'search_team', 'search_prefecture'
    end
  end
  resources :reactions, only:[:create]
  resources :matching, only:[:index]
  resources :chat, only:[:create] 
  resources :notifications, only: [:index]
  resources :message, only:[:show, :create]
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :team
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader

  with_options presence: true do
    validates :image
    validates :name,   length: { maximum: 30 }
    validates :text,   length: { maximum: 191 }
    validates :team_id
  end

  def self.search(search)
    if search != ''
      Tweet.where(['text LIKE(?) OR name LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      Tweet.order('created_at DESC')
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def show
    @team = Team.find(params[:id])
    @tweets = Tweet.where(team_id: @team.id).includes(:user)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.valid?
      @tweet.save
      redirect_to tweet_path(@tweet.team_id)
    else
      render :new
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(tweet_params)
    if @tweet.valid?
      @tweet.save
      redirect_to tweet_path(@tweet.team_id)
    else
      render :discussion
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to chat_home_index_path
  end

  def discussion
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(tweet_id: @tweet.id).includes(:user)
  end

  def search
    @tweets = Tweet.search(params[:keyword])
  end

  private

  def tweet_params
    params.require(:tweet).permit(:name, :image, :text, :team_id).merge(user_id: current_user.id)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/discussion.html.erb
<div class="discussion">
<%= render 'shared/header'%>
  <div class="container">
    <div class="discussion_tweet">
      <%= render partial: "shared/tweet", locals:{tweet: @tweet} %>
    </div>
    <div class="discussion_user">
      <% if user_signed_in? %>
        <% if current_user.id == @tweet.user_id %>
          <div class="discussion_user_edit userAction_common">
            <%= link_to(content_tag(:i, "", class: 'fas fa-cog fa-2x'), edit_tweet_path(@tweet.id)) %>
          </div>
          <div class="discussion_user_destroy userAction_common">
            <%= link_to(content_tag(:i, "", class: 'fa fa-trash fa-2x'),tweet_path(@tweet.id), method: :delete) %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="discussion_comment">
      <% if current_user %>
        <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
          <%= f.text_area :text, placeholder: "コメントしよう！", rows:"2", class:"form-control" %>
          <%= f.submit "コメント", class:"discussion_comment_btn" %>
        <% end %>
      <% end %>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <div class="discussion_comment_each">
            <strong><%= link_to comment.user.nickname, user_path(comment.user.id) %>
            <%= comment.text %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="tweet_new">
<%= render 'shared/header'%>
<header class="header">
    <div>投稿編集</div>
  </header>
 <div class="container">
   <%= form_with(model: @tweet, local: true) do |form| %>
     <%= render partial: "shared/form", locals: { f: form } %>
   <% end %>
 </div>
</div>

app/views/tweets/new.html.erb
<div class="tweet_new">
<%= render 'shared/header'%>  
  <header class="header">
    <div>新規投稿</div>
  </header>
 <div class="container">
   <%= form_with(model: @tweet, local: true) do |f| %>
     <%= render 'shared/error_messages', model: f.object %>
     <%= render partial: "shared/form", locals: { f: f } %>
   <% end %>
 </div>
</div>

app/views/tweets/search.html.erb
<div class="search">
<%= render 'shared/header'%>    
  <div class="container">
    <div class="row search_head">
      <div class="search_head_post">
        <%= link_to new_tweet_path, class:"search_head_post_btn" do %>
          <div class="search_head_post_btn_icon"><i class="fa fa-edit fa-2x"></i></div>
        <% end %>
      </div>
      <div class="search_head_search">
        <%= form_with(url: search_tweets_path, local: true, method: :get, class: "form-inline") do |f| %>
          <%= f.text_field :keyword, placeholder: '投稿を検索', class: "form-control" %>
          <%= f.submit "検索", class:"btn btn-outline-warning", style:"margin-left: 70px;" %>
        <% end %>
    </div>
    <div class="row search_tweets">
      <% @tweets.each do |tweet| %>
        <div class="search_tweets_each">
          <%= render partial: "shared/tweet", locals: { tweet: tweet} %>
        </div>
      <% end %>
    </div>
</div>

app/views/tweets/show.html.erb
<div class="tweet_show">
<%= render 'shared/header'%>                 
  <div class="container">
    <div class="row tweet_show_team">
      <%= image_tag "#{@team.image}", class:"img-fluid tweet_show_team_logo", size:"150x150" %>
    </div>
    <div class="tweet_show_table">
      <table>
        <tr>
          <th>チーム名</th>
          <th><%= @team.name%></th>
        </tr>
        <tr>
          <td class="icon coach">ヘッドコーチ👨</td>
          <td><%= @team.coach %></td>
        </tr>
        <tr>
          <td class="icon home">本拠地🗾</td>
          <td><%= @team.home %></td>
        </tr>
        <tr>
          <td class="icon character"></td>
          <td><%= @team.character %></td>
        </tr>
        <tr>
          <td class="icon ranking">順位</td>
          <td><%= @team.ranking %></td>
        </tr>
      </table>
      <%# <div class="tweet_show_map"> %>
        <%# <input id="address" type="textbox" value="= @team.home"> %>
        <%# <input type="button" class="btn btn-outline-success tweet_show_map_button" value="クリック!" onclick="codeAddress()"> %>
        <%# <div id='map'></div> %>
      <%# </div> %>
    </div>

    <div class="row tweet_show_article">
      <% @tweets.each do |tweet| %>
        <div class="tweet_show_article_each">
          <%= render partial: 'shared/tweet',locals:{tweet:tweet} %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
let map
let geocoder
const display = document.getElementById('display')
function initMap(){
  geocoder = new google.maps.Geocoder()
  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 35.66657694757677, lng: 139.698588417325 },
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 35.66657694757677, lng:139.698588417325 },
    map: map
  });
}

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
      display.textContent = "検索結果：" + results[ 0 ].geometry.location
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC6maqMN_sHGgta73vNZim4-ofbLnEGCXg&callback=initMap" async defer></script>