config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{ 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root  'home#index'

  resources :home, only:[:index] do
    collection do
      get 'chat', 'game', 'seek'
    end
  end
  resources :tweets do
    member do
      get 'discussion'
    end
    collection do
      get 'search'
    end
    resources :comments, only: [:create]
  end

  resources :users,  only:[:index, :show] do
    collection do
      get 'follow_team', 'follow_prefecture', 'search_team', 'search_prefecture'
    end
  end
  resources :reactions, only:[:create]
  resources :matching, only:[:index]
  resources :chat, only:[:create] 
  resources :notifications, only: [:index]
  resources :message, only:[:show, :create]
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  has_many :tweets
  has_many :room_users
  has_many :messages
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :sns_credentials
  belongs_to_active_hash :team
  belongs_to_active_hash :prefecture
  mount_uploader :image, ImageUploader

  enum sex: { 男: 0, 女: 1 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字混合で入力してください' }

  with_options presence: true do
    validates :image
    validates :nickname, length: { maximum: 30 }
    validates :sex
    validates :birthday
    validates :team_id
    validates :prefecture_id
    validates :request, length: { maximum: 60 }
    validates :self_introduction, length: { maximum: 191 }
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env['omniauth.auth'])
    @user = sns_info[:user]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    follow_team_users_path(resource)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end
  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.where.not(id: current_user.id)
  end

  def search_team
    @users = User.where(team_id: current_user.team_id).where.not(id: current_user.id)
  end

  def search_prefecture
    @users = User.where(prefecture_id: current_user.prefecture_id).where.not(id: current_user.id)
  end

  def show
    @user = User.find(params[:id])
    @reaction = Reaction.where(to_user_id: @user.id).where(from_user_id: current_user.id)
  end

  def follow_team
    @users = User.where(team_id: current_user.team_id).where.not(id: current_user.id)
  end

  def follow_prefecture
    @users = User.where(prefecture_id: current_user.prefecture_id).where.not(id: current_user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/follow_prefecture.html.erb
<div class="follow">
  <%= render 'shared/header' %>
  <h5 class="follow_text">近くに住んでいる方をフォローしてみませんか？</h5>
  <div class="container"> 
    <div class=" row follow_user">
      <% @users.each do |user|%>
        <ul class="follow_user_each">
          <li class="follow_user_each_img">
            <%= image_tag user.image.url(:thumb), size:"100x100" %>
          </li>
          <li class="follow_user_each_information">
            <%= link_to user_path(user.id) do %>
            <%= user.nickname %>
            <% end %>
            <%=  user.request %>
          </li>
          <li class="follow_user_each_follow">
            <%= link_to reactions_path(user_id: user.id, reaction: 'like'), method: :post do %>
            <div><i class="fa fa-thumbs-up fa-2x good" style="color: darkorange;"></i></div>
            <div class="fas fa-check fa-2x check" style="display: none; color: darkorange;"></div>
            <% end %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
    <div class="follow_move">
      <div><%= link_to 'マイページに戻る', user_path(current_user.id) %></div>
    </div>
</div>

  

app/views/users/follow_team.html.erb
<div class="follow">
  <%= render 'shared/header' %>
  <h5 class="follow_text">好きなチームが同じ方をフォローしてみませんか？</h5>
  <div class="container"> 
    <div class=" row follow_user">
      <% @users.each do |user|%>
        <ul class="follow_user_each">
          <li class="follow_user_each_img">
            <%= image_tag user.image.url(:thumb), size:"100x100" %>
          </li>
          <li class="follow_user_each_information">
            <%= link_to user_path(user.id) do %>
            <%= user.nickname %>
            <% end %>
            <%=  user.request %>
          </li>
          <li class="follow_user_each_follow">
            <%= link_to reactions_path(user_id: user.id, reaction: 'like'), method: :post do %>
            <div class="fa fa-thumbs-up fa-2x good" style="color: darkorange;"></div><span id="follow"></span>
            <div class="fas fa-check fa-2x check" style="display: none; color: darkorange;"></div>
            <% end %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
    <div class="follow_move">
      <div class="follow_move_next"><%= link_to '次へ', follow_prefecture_users_path, style:"color: darkorange;"%></div>
      <div class="follow_move_skip"><%= link_to 'マイページに戻る', user_path(current_user.id), style:"color: darkorange;"%></div>
    </div>
</div>

  

app/views/users/index.html.erb
<%= render 'shared/header' %>
<div id="loading">
  <div class="spinner"></div>
</div>

<div class="topPage">
  <nav class="nav">
    <ul>
      <li class="personIcon"><%= link_to(content_tag(:i, "", class: 'fas fa-2x fa-user'), user_path(current_user.id)) %></li>
      <li class="appIcon"><%= link_to image_tag("icon.png"), users_path %></li>
      <li class="messageIcon"><%= link_to(content_tag(:i, "", class:'fas fa-2x fa-2x fa-comments'), matching_index_path) %></li>
    </ul>
  </nav>
    <div class="search-parent">
      <div class="btn-menu"><i class="fas fa-search fa-2x btn-menu-search"></i></div>
      <div class="search-team"><%= link_to 'あなたと好きなチームが同じ人を表示', search_team_users_path, style:'color: white;' 'text-decoration: none;'%></div>
      <div class="search-prefecture"><%= link_to 'あなたと登録した都道府県が同じ人を表示', search_prefecture_users_path, style:'color: white;' 'text-decoration: none;' %></div>
    </div>
  <div id="tinderslide">
    <ul>
      <% @users.each do |user| %>
        <li data-user_id="<%= user.id %>">
          <span><%= link_to user.nickname, user_path(user.id), class:"userName fa fa-child" %></span>
          <span class="userTeam"><%= user.team.name %></span>
          <span class="userPrefecture"><%= user.prefecture.name %></span>
          <div class="userRequest"><%= user.request%></div>
          <%= image_tag "#{user.image}", class:"img-fluid"%>
          <div class="like"></div>
          <div class="dislike"></div>
        </li>
      <% end %>
    </ul>
    <div class="noUser">近くに相手がいません。</div>
  </div>
  <div class="actions" id="actionBtnArea">
      <a href="#" class="dislike"><i class="fa fa-thumbs-down fa-2x"></i></a>
      <a href="#" class="like"><i class="fa fa-thumbs-up fa-2x"></i></a>
  </div>
</div>
<script>
  let usersNum = <%= @users.length %>
  let currentUserIndex = 0;
  let postReaction = function (user_id, reaction) {
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
        }
    });
    $.ajax({
      type: "POST",
      url: "<%= reactions_path %>",
      data: {
        user_id: user_id,
        reaction: reaction,
      },
      success: function(j_data){
        console.log("success")
      }
    });
  }
  $("#tinderslide").jTinder({
    onDislike: function (item) {
      currentUserIndex++;
      checkUserNum();
      let user_id = item[0].dataset.user_id
      postReaction(user_id, 'dislike')
    },
    onLike: function (item) {
      currentUserIndex++;
      checkUserNum();
      let user_id = item[0].dataset.user_id
      postReaction(user_id, 'like')
    },
    animationRevertSpeed: 200,
    animationSpeed: 400,
    threshold: 1,
    likeSelector: '.like',
    dislikeSelector: '.dislike'
  });
  $('.actions .like, .actions .dislike').click(function(e){
    e.preventDefault();
    $("#tinderslide").jTinder($(this).attr('class'));
  });

  function checkUserNum() {
    if (currentUserIndex === usersNum){
      $(".noUser").addClass("is-active");
      $("#actionBtnArea").addClass("is-none")
      return;
    }
  }
</script>

app/views/users/search_prefecture.html.erb
<%= render 'shared/header' %>
<div id="loading">
  <div class="spinner"></div>
</div>

<div class="topPage">
  <nav class="nav">
    <ul>
      <li class="personIcon"><%= link_to(content_tag(:i, "", class: 'fas fa-2x fa-user'), user_path(current_user.id)) %></li>
      <li class="appIcon"><%= link_to image_tag("icon.png"), users_path %></li>
      <li class="messageIcon"><%= link_to(content_tag(:i, "", class:'fas fa-2x fa-2x fa-comments'), matching_index_path) %></li>
    </ul>
  </nav>
    <div class="search-parent">
      <div class="btn-menu"><i class="fas fa-search fa-2x btn-menu-search"></i></div>
      <div class="search-team"><%= link_to 'あなたと好きなチームが同じ人を表示', search_team_users_path, style:'color: white;' 'text-decoration: none;' %></div>
      <div class="search-prefecture"><%= link_to 'あなたと登録した都道府県が同じ人を表示', search_prefecture_users_path, style:'color: white;' 'text-decoration: none;' %></div>
    </div>
  <div id="tinderslide">
    <ul>
      <% @users.each do |user| %>
        <li data-user_id="<%= user.id %>">
          <span><%= link_to user.nickname, user_path(user.id), class:"userName fa fa-child" %></span>
          <span class="userTeam"><%= user.team.name %></span>
          <span class="userPrefecture"><%= user.prefecture.name %></span>
          <div class="userRequest"><%= user.request%></div>
          <%= image_tag "#{user.image}", class:"img-fluid"%>
          <div class="like"></div>
          <div class="dislike"></div>
        </li>
      <% end %>
    </ul>
    <div class="noUser">近くに相手がいません。</div>
  </div>
  <div class="actions" id="actionBtnArea">
      <a href="#" class="dislike"><i class="fa fa-thumbs-down fa-2x"></i></a>
      <a href="#" class="like"><i class="fa fa-thumbs-up fa-2x"></i></a>
  </div>
</div>
<script>
  let usersNum = <%= @users.length %>
  let currentUserIndex = 0;
  let postReaction = function (user_id, reaction) {
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
        }
    });
    $.ajax({
      type: "POST",
      url: "<%= reactions_path %>",
      data: {
        user_id: user_id,
        reaction: reaction,
      },
      success: function(j_data){
        console.log("success")
      }
    });
  }
  $("#tinderslide").jTinder({
    onDislike: function (item) {
      currentUserIndex++;
      checkUserNum();
      let user_id = item[0].dataset.user_id
      postReaction(user_id, 'dislike')
    },
    onLike: function (item) {
      currentUserIndex++;
      checkUserNum();
      let user_id = item[0].dataset.user_id
      postReaction(user_id, 'like')
    },
    animationRevertSpeed: 200,
    animationSpeed: 400,
    threshold: 1,
    likeSelector: '.like',
    dislikeSelector: '.dislike'
  });
  $('.actions .like, .actions .dislike').click(function(e){
    e.preventDefault();
    $("#tinderslide").jTinder($(this).attr('class'));
  });

  function checkUserNum() {
    if (currentUserIndex === usersNum){
      $(".noUser").addClass("is-active");
      $("#actionBtnArea").addClass("is-none")
      return;
    }
  }
</script>

app/views/users/search_team.html.erb
<%= render 'shared/header' %>
<div id="loading">
  <div class="spinner"></div>
</div>

<div class="topPage">
  <nav class="nav">
    <ul>
      <li class="personIcon"><%= link_to(content_tag(:i, "", class: 'fas fa-2x fa-user'), user_path(current_user.id)) %></li>
      <li class="appIcon"><%= link_to image_tag("icon.png"), users_path %></li>
      <li class="messageIcon"><%= link_to(content_tag(:i, "", class:'fas fa-2x fa-2x fa-comments'), matching_index_path) %></li>
    </ul>
  </nav>
    <div class="search-parent">
      <div class="btn-menu"><i class="fas fa-search fa-2x btn-menu-search"></i></div>
      <div class="search-team"><%= link_to 'あなたと好きなチームが同じ人を表示', search_team_users_path, style:'color: white;' 'text-decoration: none;' %></div>
      <div class="search-prefecture"><%= link_to 'あなたと登録した都道府県が同じ人を表示', search_prefecture_users_path, style:'color: white;' 'text-decoration: none;' %></div>
    </div>
  <div id="tinderslide">
    <ul>
      <% @users.each do |user| %>
        <li data-user_id="<%= user.id %>">
          <span><%= link_to user.nickname, user_path(user.id), class:"userName fa fa-child" %></span>
          <span class="userTeam"><%= user.team.name %></span>
          <span class="userPrefecture"><%= user.prefecture.name %></span>
          <div class="userRequest"><%= user.request%></div>
          <%= image_tag "#{user.image}", class:"img-fluid"%>
          <div class="like"></div>
          <div class="dislike"></div>
        </li>
      <% end %>
    </ul>
    <div class="noUser">近くに相手がいません。</div>
  </div>
  <div class="actions" id="actionBtnArea">
      <a href="#" class="dislike"><i class="fa fa-thumbs-down fa-2x"></i></a>
      <a href="#" class="like"><i class="fa fa-thumbs-up fa-2x"></i></a>
  </div>
</div>
<script>
  let usersNum = <%= @users.length %>
  let currentUserIndex = 0;
  let postReaction = function (user_id, reaction) {
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
        }
    });
    $.ajax({
      type: "POST",
      url: "<%= reactions_path %>",
      data: {
        user_id: user_id,
        reaction: reaction,
      },
      success: function(j_data){
        console.log("success")
      }
    });
  }
  $("#tinderslide").jTinder({
    onDislike: function (item) {
      currentUserIndex++;
      checkUserNum();
      let user_id = item[0].dataset.user_id
      postReaction(user_id, 'dislike')
    },
    onLike: function (item) {
      currentUserIndex++;
      checkUserNum();
      let user_id = item[0].dataset.user_id
      postReaction(user_id, 'like')
    },
    animationRevertSpeed: 200,
    animationSpeed: 400,
    threshold: 1,
    likeSelector: '.like',
    dislikeSelector: '.dislike'
  });
  $('.actions .like, .actions .dislike').click(function(e){
    e.preventDefault();
    $("#tinderslide").jTinder($(this).attr('class'));
  });

  function checkUserNum() {
    if (currentUserIndex === usersNum){
      $(".noUser").addClass("is-active");
      $("#actionBtnArea").addClass("is-none")
      return;
    }
  }
</script>

app/views/users/show.html.erb
<%= render 'shared/header' %>
<div class='usershowPage'>
  <div class='container'>
    <header class="header">
      <% if @user.id == current_user.id %>
        <div class='header_seek'>
          <%= link_to users_path, class:"header_seek_btn" do %>
            <div class="header_seek_btn_icon"><i class="fas fa-search fa-3x"></i></div>
          <% end %>
        </div>
        <div class='header_notification'>
          <%= link_to notifications_path, class:"header_notification_btn" do %>
            <div class="header_notification_btn_icon"><i class="fas fa-bell fa-3x"></i></div>
          <% end %>
        </div>
        <div class="header_tweet">
          <%= link_to new_tweet_path, class:"header_tweet_btn" do %>
            <div class="header_tweet_btn_icon"><i class="fa fa-edit fa-2x"></i></div>
          <% end %>
        </div>
      <% else %>
          <% if @reaction != [] %>
            <div class='header_already'><span class="header_already_text">フォロー済</span></div>
          <% else %>
            <div class='header_follow'>
              <%= link_to reactions_path(user_id: @user.id, reaction: 'like'), method: :post do %>
                <div class="fa fa-thumbs-up fa-2x good" style="color: darkorange;"></div>
              <% end %>
            </div>
          <% end %>
      <% end %>
    </header>
    <div class='userInfo'>
      <div class='userInfo_img'>
        <%= image_tag @user.image.url(:thumb) %>
      </div>
      <div class='userInfo_name'><%= @user.nickname%>
        <% if @user.sex == 0 %>
          <i class="fas fa-mars" style="color: blue;"></i>
          <% else %>
          <i class="fas fa-venus" style="color: red;"></i>
        <% end %>
      </div>
      <div class='userInfo_birthday'><i class="fas fa-birthday-cake userInfo_birthday_icon"></i>
      <%= @user.birthday%>
      <%= image_tag "#{@user.team.image}", class:"img-fluid userInfo_birthday_team", size:"65x65" %>
      <%= "#{@user.prefecture.name}在住" %>
      </div>
      <div class='userInfo_selfIntroduction'><%= @user.self_introduction %></div>
    </div>
    </div>
    <% if current_user.id == @user.id %>
      <div class='userAction'>
        <div class="userAction_edit userAction_common">
          <%= link_to(content_tag(:i, "", class: 'fa fa-street-view fa-2x '), edit_user_registration_path) %>
          <span>情報を編集</span>
        </div>
        <div class='userAction_logout userAction_common'>
          <%= link_to(content_tag(:i, "", class: 'fas fa-cog fa-2x'), destroy_user_session_path, method: :delete) %>
          <span>ログアウト</span>
        </div>
      </div>
    <% end %>
    <div class="userPost">
      <div class="userPost_icon"><i class="fa fa-desktop "></i> </div>
      <div class="userPost_card">
        <% if @user.tweets.blank? %>
        <div>まだ投稿はありません</div>
        <% else %>
          <%= render partial: 'shared/tweet', collection: @user.tweets %>
        <% end %>
      </div>
  </div>
</div>