config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{ 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root  'home#index'

  resources :home, only:[:index] do
    collection do
      get 'chat', 'game', 'seek'
    end
  end
  resources :tweets do
    member do
      get 'discussion'
    end
    collection do
      get 'search'
    end
    resources :comments, only: [:create]
  end

  resources :users,  only:[:index, :show] do
    collection do
      get 'follow_team', 'follow_prefecture', 'search_team', 'search_prefecture'
    end
  end
  resources :reactions, only:[:create]
  resources :matching, only:[:index]
  resources :chat, only:[:create] 
  resources :notifications, only: [:index]
  resources :message, only:[:show, :create]
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="major_footer">
  <div class="card"  style='background-color: darkorange; border: 1px solid white;'>
    <h6 class="card-header text-light" style="border-bottom:2px solid white;">MatchApp</h6>
    <div class="text-light">
      COPYRIGHT © ZAB Inc. All rights Reserved.
    </div>
  </div>
</div>

app/views/shared/_form.html.erb
<div class="postForm">
  <label for="file_photo" class="rounded-circle postForm_img">
    <div class="postForm_img_description">画像をアップロード</div>
    <i class="fas fa-camera fa-3x"></i>
    <%= f.file_field :image, id: "file_photo" %>
  </label>

  <div class="ImgPreview" id="userImgPreview">
    <img id="thumbnail" class="ImgPreview_content">
    <p class="ImgPreview_text">画像をアップロード済み</p>
  </div>

  <div class="form-group">
    <%= f.label :テーマ%>
    <%= f.label :必須, class:"badge badge-danger" %><br/>
    <%= f.text_field :name, placeholder: "例）試合観戦", class:"form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :ニュース %>
    <%= f.label :必須, class:"badge badge-danger" %><br/>
    <%= f.text_area :text, placeholder: "例）今日は名古屋ダイヤモンドドルフィンズの試合観戦！家族で大盛りあがり!最後にはなんと......", rows: "3", class:"form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :どのチームのニュース？ %>
      <%= f.label :必須, class:"badge badge-danger" %><br/>
      <%= f.collection_select(:team_id, Team.all, :id, :name,{include_blank: "🏀"}, { class:"form-control"}) %><br />
  </div> 

  <div class="text-center">
    <%= f.submit "投稿する", class:"btn submitBtn" %>
  </div>

</div>

app/views/shared/_header.html.erb
<div class="major_header">
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: darkorange; border:1px solid white">
    <%= link_to 'MatchApp', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="border:1px solid white;">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to '新規登録', new_user_registration_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'ログイン', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "ニュース", chat_home_index_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'クイズ', game_home_index_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%=link_to "Bリーグ(リンク）", "https://www.bleague.jp/", class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "仲間を探す", users_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "投稿する", new_tweet_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%=link_to "チャットページ", matching_index_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%=link_to "通知", notifications_path, class:"nav-link"%>
          </li>
        <% end %>
        <li class="nav-item">
          <a href="https://lin.ee/pHke6nm"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"></a>
        </li>
      </ul>
    </div>
  </nav>
</div>

app/views/shared/_tweet.html.erb
<div class="card" style="width: 20rem; text-align: center;">
<%# <div class="container"> %>
  <div class="card_body">
    <h5 class="card-text" style="margin-bottom: 10px;"><%= tweet.name%></h5>
  </div>
    <%= link_to discussion_tweet_path(tweet.id)  do %>
      <%= image_tag "#{tweet.image}", class:"img-fluid", style:"height: 30vh; weigth: 20rem;" %>
    <% end %>
  <div class="card-body">
    <p class="card-text"><%= tweet.text %></p>
    <p>投稿者 : <%= link_to "#{tweet.user.nickname}", user_path(tweet.user.id) %></p>
  </div>
<%# </div> %>
</div>