config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{ 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root  'home#index'

  resources :home, only:[:index] do
    collection do
      get 'chat', 'game', 'seek'
    end
  end
  resources :tweets do
    member do
      get 'discussion'
    end
    collection do
      get 'search'
    end
    resources :comments, only: [:create]
  end

  resources :users,  only:[:index, :show] do
    collection do
      get 'follow_team', 'follow_prefecture', 'search_team', 'search_prefecture'
    end
  end
  resources :reactions, only:[:create]
  resources :matching, only:[:index]
  resources :chat, only:[:create] 
  resources :notifications, only: [:index]
  resources :message, only:[:show, :create]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    agent = Mechanize.new
    page = agent.get('https://basketballking.jp/news/category/bl')
    @elements = page.search('.news-category-list__vertical__title')
  end

  def chat
    @tweets = Tweet.all
    @teams = Team.all
  end

  def game
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/chat.html.erb
<div class="conversation">
<%= render 'shared/header'%>    
  <div class="container">
    <div class="row conversation_search">
      <h5 class="col conversation_search_text">チーム毎のニュースを確認できます</h5>
      <%= form_with(url: search_tweets_path, local: true, method: :get, class: "form-inline conversation_search_search") do |f| %>
        <%= f.text_field :keyword, placeholder: 'ニュースを検索', class: "form-control" %>
        <%= f.submit "検索", class:"btn btn-outline-warning" %>
      <% end %>
    </div>
    
    <div class="row conversation_teams">
      <% @teams.each do |team| %>
        <div class="col-xs-4 conversation_teams_each"> 
          <%= link_to tweet_path(team.id) do %>
          <%= image_tag "#{team.image}", class:"img-fluid", size:"159x159" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<%= render 'shared/footer'%>
</div>

app/views/home/game.html.erb
<%= render 'shared/header' %>
<div class="other">
  <div class="container"> 
    <div class="row other_head">🏀バスケットボール検定🏀</div>
    <div class="row other_q" id="text_q"></div>
    <div class="row other_s" id="text_s" ></div>
    <div class="row other_foot">前の問題の答え</div>
    <div class="row other_a" id="text_a"></div>
  </div>
</div>
<%= render 'shared/footer' %>

<script type="text/javascript">

qa = new Array();
    qa[0] = ["バスケットの神様と呼ばれるNBA史上最高の選手は？","レブロン・ジェームス","コービー・ブライアント","ケビン・ガーネット","マイケル・ジョーダン",4];
    qa[1] = ["日本人初となるNBAドラフト1巡目指名された八村塁選手ですが、どのチームから指名されたでしょうか？","ワシントン・ウィザーズ","ロサンゼルス・レイカーズ","クリーブラント・キャバリアーズ","ヒューストン・ロケッツ",1];
    qa[2] = ["Bリーグ初年度の優勝チームは？","宇都宮ブレックス","アルバルク東京","川崎ブレイブサンダース","名古屋ダイヤモンドドルフィンズ",1];
    qa[3] = ["Bリーグ初年度のMVPは？","田中大貴","富樫勇樹","ニック・ファジーカス","八村塁", 3];
    qa[4] = ["この中でNBAのチームに在籍していたことがない選手は？","ライアン・ロシター","ジョシュ・ハレルソン","ニック・ファジーカス","田臥勇太",1];
    qa[5] = ["比江島慎の身長は？","188cm","190cm","192cm","195cm",2];
    qa[6] = ["B1リーグのチーム数は？","15","20","25","30",2];
    qa[7] = ["B2リーグのチーム数は？","12","14","16","20",3];
    qa[8] = ["名古屋ダイヤモンドドルフィンズのマスコットの名前は？","ドルちゃん","ブラックマンバ","エドワード","ディー・ディー",4];
    qa[9] = ["斎藤拓実の出身校として誤っているものは？","桐光学園高校","明治大学","白鳥中学","福岡第一高校",4];

    q_sel = 4;
    q_max = 10;
    setReady();

    function setReady(){
      count = 0;
      answers = new Array();
      randoms = new Array();
      quiz();
    };

    function getRandom(){
      let random_1 = Math.floor(Math.random()*10)
      if(!(randoms.includes(random_1))){
        randoms.push(random_1);
        return random_1;
      }else{
        let random_2 = random_1;
        while(randoms.includes(random_2)){ 
          let random_2 = Math.floor(Math.random()*10)
          if(!(randoms.includes(random_2))){
            randoms.push(random_2);
            return random_2;
          }
        }
      }
    }

    function quiz(){
      let s;
      let n;
      random = getRandom();
      document.getElementById("text_q").innerHTML = "第"+(count+1)+"問🏀"+qa[random][0];
      s = "";
      for(n=1; n<=q_sel; n++){
        if(qa[random][n] != ""){
          s += "<a href='javascript:answer(" + n + ")' class='other_choice'>" + n + "：" + qa[random][n] + "</a>";
        }
      }
      document.getElementById("text_s").innerHTML = s;
    };

    function answer(num){
      let s;
      s = (count+ 1)+"問目：";
      if(num === qa[random][q_sel+1]){
        answers[count] = "○";
      }else{
        answers[count] = "✗";
      }
      s += answers[count]+qa[random][num];
      document.getElementById("text_a").innerHTML = s;

      count++;
      if(count<q_max){
        quiz();
      }else{
        s = "<table border='2'><caption style='color: darkorange; margin-top: 60px;'>8問以上正解で自慢しよう！</caption>";
        s += "<tr><th>問題</th>";
        for(n=0; n<qa.length; n++){
          s += "<th>"+(n+1)+"</th>";
        }
        s += "</tr>";
        s += "<tr><th>成績</th>";
        for(n=0; n<qa.length; n++){
          s += "<td>" + answers[n] + "</td>";
        }
        s += "</tr>";
        s += "</table>";
        document.getElementById("text_q").innerHTML = s;

        s = "<a href='javascript:history.back()' style='color:white; margin-top:30px; text-decoration-color: darkorange;'>トップページ</a>";
        s += "<a href='javascript:setReady()' style='color:white; margin-top:30px; text-decoration-color: darkorange;'>最初から</a>";
        document.getElementById("text_s").innerHTML = s;
      }
    };

</script>

app/views/home/index.html.erb
<div class="summary">
<%= render 'shared/header' %>
  <div class="container">
    <div class="summary_top">
      <div class="col summary_timer">
        <h6>東京五輪バスケ開催まで</h6>
        <p class="h5"><span id="day" class="h4"></span>日<span id="hour" class="h4"></span>時間<span id="min" class="h4"></span>分<span id="sec" class="h4"></span>秒</p>
      </div>
      <div class="summary_show">
        <h5><strong>バスケ</strong>専用マッチングアプリ</h5>
      </div>
    </div>
    <div class="row summary_up">
      <div class="col summary_up_title">
        <h4><span class="summary_up_title_team">チームメイトを探したい</span><br/>
        <span class="summary_up_title_match">他のチームと試合を組みたい</span><br/>
        <span class="summary_up_title_friends">応援仲間を見つけたい</span></h4>
        <h3 class="summary_up_title_hope"><strong class="h1" style="color: darkorange;">MatchApp</strong>で見つかります</h3>
      </div>
      <div class="col summary_up_search">
        <%= link_to seek_home_index_path, class:"summary_up_btn" do %>
          <div class="summary_up_btn_icon">探しに行く</div>
        <% end %>
      </div>
    </div>
    <div class="row summary_down">
      <div class="col-xs-4">
        <%= link_to chat_home_index_path, class:"summary_down_news" do %>
          <div class="summary_down_new_text">NEWS</div>
        <% end %>
      </div>
      <div class="col-xs-4">  
        <%= link_to game_home_index_path, class:"summary_down_btn" do %>
          <div class="summary_down_btn_icon"><i class="fa fa-gamepad"></i></div>
        <% end %>
      </div>
      <div class="col-xs-4">
        <a href="https://lin.ee/pHke6nm" class="summary_down_line fab fa-line fa-4x"></a>
      </div>
    </div>
    <div class="summary_news">
      <div class="summary_news_title">〜最新NEWS〜</div>
      <% @elements.each do |e| %>
        <ul>
          <li class='summary_news_text'><%= "#{e.inner_text}" %></li>
        </ul>
      <% end %>
    </div>
  </div>
<%= render 'shared/footer' %>

app/views/home/other.html.erb
<%= render 'shared/header' %>
<div class="other">
  <div class="container"> 
    <div class="row other_head">🏀バスケットボール検定🏀</div>
    <div class="row other_q" id="text_q"></div>
    <div class="row other_s" id="text_s" ></div>
    <div class="row other_foot">前の問題の答え</div>
    <div class="row other_a" id="text_a"></div>
  </div>
</div>
<%= render 'shared/footer' %>

<script type="text/javascript">

qa = new Array();
    qa[0] = ["バスケットの神様と呼ばれるNBA史上最高の選手は？","レブロン・ジェームス","コービー・ブライアント","ケビン・ガーネット","マイケル・ジョーダン",4];
    qa[1] = ["日本人初となるNBAドラフト1巡目指名された八村塁選手ですが、どのチームから指名されたでしょうか？","ワシントン・ウィザーズ","ロサンゼルス・レイカーズ","クリーブラント・キャバリアーズ","ヒューストン・ロケッツ",1];
    qa[2] = ["Bリーグ初年度の優勝チームは？","宇都宮ブレックス","アルバルク東京","川崎ブレイブサンダース","名古屋ダイヤモンドドルフィンズ",1];
    qa[3] = ["Bリーグ初年度のMVPは？","田中大貴","富樫勇樹","ニック・ファジーカス","八村塁", 3];
    qa[4] = ["この中でNBAのチームに在籍していたことがない選手は？","ライアン・ロシター","ジョシュ・ハレルソン","ニック・ファジーカス","田臥勇太",1];
    qa[5] = ["比江島慎の身長は？","188cm","190cm","192cm","195cm",2];
    qa[6] = ["B1リーグのチーム数は？","15","20","25","30",2];
    qa[7] = ["B2リーグのチーム数は？","12","14","16","20",3];
    qa[8] = ["名古屋ダイヤモンドドルフィンズのマスコットの名前は？","ドルちゃん","ブラックマンバ","エドワード","ディー・ディー",4];
    qa[9] = ["斎藤拓実の出身校として誤っているものは？","桐光学園高校","明治大学","白鳥中学","福岡第一高校",4];

    q_sel = 4;
    q_max = 10;
    setReady();

    function setReady(){
      count = 0;
      answers = new Array();
      randoms = new Array();
      quiz();
    };

    function getRandom(){
      let random_1 = Math.floor(Math.random()*10)
      if(!(randoms.includes(random_1))){
        randoms.push(random_1);
        return random_1;
      }else{
        let random_2 = random_1;
        while(randoms.includes(random_2)){ 
          let random_2 = Math.floor(Math.random()*10)
          if(!(randoms.includes(random_2))){
            randoms.push(random_2);
            console.log(randoms);
            return random_2;
          }
        }
      }
    }

    function quiz(){
      let s;
      let n;
      random = getRandom();
      document.getElementById("text_q").innerHTML = "第"+(count+1)+"問🏀"+qa[random][0];
      s = "";
      for(n=1; n<=q_sel; n++){
        if(qa[random][n] != ""){
          s += "<a href='javascript:answer(" + n + ")' class='other_choice'>" + n + "：" + qa[random][n] + "</a>";
        }
      }
      document.getElementById("text_s").innerHTML = s;
    };

    function answer(num){
      let s;
      s = (count+ 1)+"問目：";
      if(num === qa[random][q_sel+1]){
        answers[count] = "○";
      }else{
        answers[count] = "✗";
      }
      s += answers[count]+qa[random][num];
      document.getElementById("text_a").innerHTML = s;

      count++;
      if(count<q_max){
        quiz();
      }else{
        s = "<table border='2'><caption style='color: darkorange; margin-top: 60px;'>8問以上正解で自慢しよう！</caption>";
        s += "<tr><th>問題</th>";
        for(n=0; n<qa.length; n++){
          s += "<th>"+(n+1)+"</th>";
        }
        s += "</tr>";
        s += "<tr><th>成績</th>";
        for(n=0; n<qa.length; n++){
          s += "<td>" + answers[n] + "</td>";
        }
        s += "</tr>";
        s += "</table>";
        document.getElementById("text_q").innerHTML = s;

        s = "<a href='javascript:history.back()' style='color:white; margin-top:30px; text-decoration-color: darkorange;'>トップページ</a>";
        s += "<a href='javascript:setReady()' style='color:white; margin-top:30px; text-decoration-color: darkorange;'>最初から</a>";
        document.getElementById("text_s").innerHTML = s;
      }
    };

</script>

app/views/home/seek.html.erb
<%= render 'shared/header' %>

<div class="loginPage">
  <div class="container">
    <div class="loginPage_contents">
      <h1 class="h3 loginPage_contents_title">バスケでつながろう</h1>
      <%= link_to "さあ、はじめよう！", users_path, class:"btn loginPage_contents_btn"%>
      <%= link_to "メールアドレスでログインする", new_user_session_path, class: "btn loginPage_contents_btn" %>
    </div>
  </div>
</div>